site_name: Notas Musicais
repo_url: https://github.com/jovycarvalho/notas_musicais.git
repo_name: ovycarvalho/notas_musicais
edit_uri: /tree/main/docs
theme: 
    name: material
    language: pt-BR
    logo: assets/logo2.png
    favicon: assets/logo2.png
markdown_extensions:
    - attr_list

extra_css:
    - stylesheet/extra.css   
